### ISSUE TITLE
Corrupted environment

### ISSUE THREAD

**Issue by cbernet** [HEP-FCC/fcc-spi#21]
Hi guys, 
I would have contacted Joschka for this kind of thing, but since he's away :-( I just file an issue here. 
There is something wrong with our initialization scripts.

When I do : 

     source /cvmfs/fcc.cern.ch/sw/0.8.1/init_fcc_stack.sh

I cannot run emacs anymore: 

```
$ emacs
emacs: symbol lookup error: /usr/lib64/libpangocairo-1.0.so.0: undefined symbol: cairo_ft_font_options_substitute
```

It works well before sourcing the init script. 

emacs is widely used, so I think we should do something (so far I have been forced to use terminal mode). 

Cheers! 

Colin

**Comment by vvolkl** [comment]
Hi Colin,

can't reproduce this issue on lxplus. Which platform / environment are you running?
Cheers,
Valentin

**Comment by cbernet** [comment]
Hi Valentin, 

Thanks for trying!

I log to lxplus, where I’m not doing anything special:

[python_toy]$ ssh lxplus
Warning: Permanently added the RSA host key for IP address '188.184.91.226' to the list of known hosts.
Last login: Wed Jun 28 15:14:46 2017 from sta01-1-88-175-213-86.fbx.proxad.net
* ********************************************************************
* Welcome to lxplus011.cern.ch, SLC, 6.9
* Archive of news is available in /etc/motd-archive
* Reminder: You have agreed to comply with the CERN computing rules
* https://cern.ch/ComputingRules
* Puppet environment: production, Roger state: production
* Foreman hostgroup: lxplus/nodes/login
* LXPLUS Public Login Service
* ********************************************************************
[~]$ echo $LD_LIBRARY_PATH 
/afs/cern.ch/user/c/cbern/local/lib <http://cern.ch/user/c/cbern/local/lib>
# at this stage, emacs works
[~]$  source /cvmfs/fcc.cern.ch/sw/0.8.1/init_fcc_stack.sh
Platform detected: x86_64-slc6-gcc62
Software taken from /cvmfs/fcc.cern.ch/sw/0.8.1 and /cvmfs/sft.cern.ch/lcg/views/LCG_88/x86_64-slc6-gcc62-opt
[~]$ emacs
emacs: symbol lookup error: /usr/lib64/libpangocairo-1.0.so.0: undefined symbol: cairo_ft_font_options_substitute

Cheers, 

Colin

**Comment by clementhelsens** [comment]
I confirm I see the same thing than Colin!
Clement

Le 28 juin 2017 à 15:37, Colin Bernet <notifications@github.com<mailto:notifications@github.com>> a écrit :

Hi Valentin,

Thanks for trying!

I log to lxplus, where I’m not doing anything special:

[python_toy]$ ssh lxplus
Warning: Permanently added the RSA host key for IP address '188.184.91.226' to the list of known hosts.
Last login: Wed Jun 28 15:14:46 2017 from sta01-1-88-175-213-86.fbx.proxad.net<http://sta01-1-88-175-213-86.fbx.proxad.net>
* ********************************************************************
* Welcome to lxplus011.cern.ch<http://lxplus011.cern.ch>, SLC, 6.9
* Archive of news is available in /etc/motd-archive
* Reminder: You have agreed to comply with the CERN computing rules
* https://cern.ch/ComputingRules
* Puppet environment: production, Roger state: production
* Foreman hostgroup: lxplus/nodes/login
* LXPLUS Public Login Service
* ********************************************************************
[~]$ echo $LD_LIBRARY_PATH
/afs/cern.ch/user/c/cbern/local/lib<http://cern.ch/user/c/cbern/local/lib> <http://cern.ch/user/c/cbern/local/lib>
# at this stage, emacs works
[~]$ source /cvmfs/fcc.cern.ch/sw/0.8.1/init_fcc_stack.sh<http://fcc.cern.ch/sw/0.8.1/init_fcc_stack.sh>
Platform detected: x86_64-slc6-gcc62
Software taken from /cvmfs/fcc.cern.ch/sw/0.8.1<http://fcc.cern.ch/sw/0.8.1> and /cvmfs/sft.cern.ch/lcg/views/LCG_88/x86_64-slc6-gcc62-opt<http://sft.cern.ch/lcg/views/LCG_88/x86_64-slc6-gcc62-opt>
[~]$ emacs
emacs: symbol lookup error: /usr/lib64/libpangocairo-1.0.so.0: undefined symbol: cairo_ft_font_options_substitute

Cheers,

Colin

**Comment by vvolkl** [comment]
Ah, I see -- for me the issue only appears only with the GUI / X-forwarding enabled. I'll try to take a look at the environment!

**Comment by cbernet** [comment]
Yes indeed, emacs is working in terminal mode. 
Thank you very much for investigating Valentin ( this is not high priority as far as I’m concerned :-) ).

Colin

**Comment by vvolkl** [comment]
The problem is connected to the LCG release, I can reproduce it just after running

`source /cvmfs/sft.cern.ch/lcg/views/LCG_88/x86_64-slc6-gcc62-opt/setup.sh`

so it is out of the FCC domain :-) I'll forward this issue to SFT and create a ticket in JIRA.

**Comment by hegner** [comment]
It seems the next LCG release has a fix in the pipeline. Will test on one of the next nightlies.

**Comment by vvolkl** [comment]
Oh, I already created the issue:
https://sft.its.cern.ch/jira/browse/SPI-981
but I can update it with your findings, if you let me know!
